In [13]:
import pandas as pd

df = pd.read_csv('data/aggregated/date/reservoir_sensors_reads.csv')
df

,CALC000041,CALC000046,CALC000103,CALC000120,CALC000125,CALC000143,CALC000152,CALC000168,CALC000713,CALC000722,CALC000735,timestamp
0,71.70435,31.38015,1.75850,12.81500,7.79500,79.57425,19.14110,39.49005,28.17150,27.42475,45.60825,2023-01-12 09:00:00
1,71.71910,31.34700,1.75775,12.74900,7.79100,83.00400,19.13120,39.31590,28.13850,27.40785,45.55810,2023-01-13 09:00:00
2,71.65910,31.33215,1.75560,12.66450,7.78200,85.01955,19.11950,39.17335,28.09875,27.39330,45.51050,2023-01-14 09:00:00
3,51.54400,31.26260,1.75450,12.60350,7.77800,86.26575,19.10015,39.05270,28.06550,27.37585,45.47350,2023-01-15 09:00:00
4,61.75660,31.26755,1.75335,12.51875,7.77240,78.60940,19.08075,38.95145,28.02850,27.35670,45.41800,2023-01-16 09:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...
805,100.56280,64.42100,1.94520,53.49150,24.07100,82.01180,72.04620,43.47840,98.49905,55.80730,77.35025,2025-04-04 09:00:00
806,100.60420,64.61000,1.96575,53.90025,24.20540,82.51555,72.73980,43.48220,98.32675,56.12975,77.62400,2025-04-05 09:00:00
807,100.64565,64.78745,1.98240,54.26515,24.31675,83.36330,73.40080,43.47110,98.10590,56.49950,77.93600,2025-04-06 09:00:00
808,100.50535,64.92250,1.99610,54.51210,24.41500,81.54280,73.45610,43.85570,97.93975,56.85850,78.14805,2025-04-07 09:00:00
809,100.06010,65.05750,2.00395,54.78850,24.50675,80.53895,73.15070,44.53335,97.82525,57.24400,78.36215,2025-04-08 09:00:00

In [14]:
df_pantans = pd.read_csv('data/simplified/metadata/reservoir_sensors_metadata.csv')
df_pantans

,sensor_id,description,dataType,location,type,unit,timeZone,publicAccess,component,componentType,...,info_river_district,info_basin,info_sub_basin,info_municipality,info_reservoir_max_capacity_(hm3),info_x_coord_utm_etrs89,info_y_coord_utm_etrs89,info_drained_basin_surface(km2),info_responsible_entity,info_state
0,CALC000041,Percentage reservoir volume,NUMBER,41.255617318 1.651034658,39,%,CET,True,080581-002,reservoir,...,ACA,EL FOIX,EL FOIX,CASTELLET I LA GORNAL,3.74,386988,4568011,293.32,AGÃˆNCIA CATALANA DE L'AIGUA,In service
1,CALC000046,Percentage reservoir volume,NUMBER,42.340588782 2.833225165,39,%,CET,True,170600-001,reservoir,...,ACA,LA MUGA,LA MUGA,DARNIUS,61.10,486262,4687606,181.20,AGÃˆNCIA CATALANA DE L'AIGUA,In service
2,CALC000103,Percentage reservoir volume,NUMBER,41.195224935 1.327889195,39,%,CET,True,430430-001,reservoir,...,ACA,EL GAIÃ€,EL GAIÃ€,"CATLLAR, EL",59.40,359786,4561777,358.45,"REPSOL PETRÃ“LEO, SA",In service
3,CALC000120,Percentage reservoir volume,NUMBER,41.134931354 0.960270444,39,%,CET,True,430537-001,reservoir,...,ACA,RIERA DE RIUDECANYES,RIERA DE RIUDECANYES,RIUDECANYES,5.32,328801,4555741,31.00,COMUNITAT DE REGANTS DEL PANTÃ€ DE RIUDECANYES,In service
4,CALC000125,Percentage reservoir volume,NUMBER,41.249642381 0.913800784,39,%,CET,True,430496-001,reservoir,...,ACA,L'EBRE,RIU DE SIURANA,CORNUDELLA DE MONTSANT,12.22,325206,4568569,60.40,AGÃˆNCIA CATALANA DE L'AIGUA,In service
5,CALC000143,Percentage reservoir volume,NUMBER,41.984436008 2.601414188,39,%,CET,True,171899-003,reservoir,...,ACA,EL TER,ALT TER,"CELLERA DE TER, LA",1.30,466982,4648125,1799.00,"ENDESA GENERACION, SA",In service
6,CALC000152,Percentage reservoir volume,NUMBER,41.968624956 2.413554059,39,%,CET,True,083036-001,reservoir,...,ACA,EL TER,ALT TER,VILANOVA DE SAU,165.26,451408,4646459,1564.00,AGÃˆNCIA CATALANA DE L'AIGUA,In service
7,CALC000713,Percentage reservoir volume,NUMBER,42.122014524 1.878559556,39,%,CET,True,082687-001,reservoir,...,ACA,EL LLOBREGAT,ALT LLOBREGAT,CERCS,109.43,407302,4663932,503.35,AGÃˆNCIA CATALANA DE L'AIGUA,In service
8,CALC000722,Percentage reservoir volume,NUMBER,42.099784969 1.58285827,39,%,CET,True,081419-003,reservoir,...,ACA,EL LLOBREGAT,EL CARDENER,NAVÃˆS,80.00,382818,4661827,197.00,AGÃˆNCIA CATALANA DE L'AIGUA,In service
9,CALC000735,Percentage reservoir volume,NUMBER,41.962942293 1.605613258,39,%,CET,True,250753-004,reservoir,...,ACA,EL LLOBREGAT,EL CARDENER,CLARIANA DE CARDENER,24.38,384452,4646602,304.99,AGÃˆNCIA CATALANA DE L'AIGUA,In service
10,CALC000168,Percentage reservoir volume,NUMBER,41.979075237 2.527357457,39,%,CET,True,171169-001,reservoir,...,ACA,EL TER,ALT TER,OSOR,233.00,460844,4647561,1773.15,"ENDESA GENERACION, SA",In service

In [21]:
dates = df["timestamp"].astype("datetime64[ns]").dt.date.to_list()
dates[-1]

datetime.date(2025, 4, 8)

In [16]:
sensor_id = df_pantans['sensor_id']
pantans = df_pantans['componentDesc']